### ISSUE TITLE
Update to Swift 4 / add license

### ISSUE THREAD

**Issue by raphlinus** [janba/SwiftMetalOSXHelloTriangle#1]
I've updated this to Swift 4 locally, and would be happy to send a PR, but in order to do so it needs to be under an open source license.

Thanks, this was useful to experiment with Metal!

**Comment by janba** [comment]
Very nice to hear that someone found this useful. I have added a license to the project. Seems to work. I will be very happy to pull your updates!

**Comment by raphlinus** [comment]
Excellent, thank you!

By the way, one of the reasons I was experimenting with this is to investigate visual artifacts on window resize; my app is currently OpenGL but I wanted to explore whether Metal would solve them; it doesn't. If you add `Thread.sleep(forTimeInterval: 0.02 * drand48())` to the end of the `draw` call, then occasionally the whole window (including titlebar) will "jump" for a frame. This is on a mid-2014 MBP running 10.12.6, with a GT750M. I've experimented with a number of variables, including energy saver gpu switching, and using only one monitor, but nothing affects this behavior. I'm curious whether this is a more pervasive problem. I've seen a lot of reports of similar on 10.13, and if I still see it when I upgrade, I'll certainly surface it to Apple.
